version: "3.8"

services:
  app:
    build:
      args:
        user: laravel
        uid: 1000
      context: ./
      dockerfile: .docker/Dockerfile
    image: laravel
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - mynetwork

  # nginx
  nginx:
    container_name: laravel-nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    networks:
      - mynetwork

  # mysql
  mysql:
    container_name: laravel-mysql
    image: mysql:5.7.38
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
      - ./docker/mysql/log:/var/log/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  # redis
  redis:
    container_name: laravel-redis
    image: redis:latest
    volumes:
      - ./.docker/redis/redis.conf:/etc/redis/redis.conf
      - ./docker/redis/log:/var/log/redis/
    networks:
      - mynetwork

  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel-phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    links:
      - mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
